# 작은 용량에 맞춘 보존/세그먼트 튜닝
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: eden-kafka
spec:
  kafka:
    config:
      log.retention.bytes: 838860800   #  800 MiB
      log.segment.bytes: 134217728     # 128 MiB
      default.replication.factor: 2
      min.insync.replicas: 1
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1